#!/usr/bin/env bash
# scripts/generate-synthetic-corpus.sh — FILE-I #1528 v0.85 helper.
#
# Generates a synthetic Go corpus of N files for use by the resource-
# pressure bench. Each file is ~1KB of valid-but-trivial Go: 1 package
# decl + 1 import + 1 exported func + 1 exported var. Enough surface
# for extraction to do real work, small enough that the IO cost is
# dominated by indexer overhead (not file contents).
#
# Usage:
#   scripts/generate-synthetic-corpus.sh <count> <output_dir>
#
# Example:
#   scripts/generate-synthetic-corpus.sh 10000 /tmp/corpus-10k

set -euo pipefail

COUNT="${1:?count is required: ./generate-synthetic-corpus.sh <count> <dir>}"
OUT="${2:?output directory is required}"

mkdir -p "${OUT}"

# Splay files across 100 directories so the indexer's gocodewalker
# isn't bottlenecked by a single directory's readdir size.
for i in $(seq 1 "${COUNT}"); do
  bucket=$(( i % 100 ))
  pkg_dir="${OUT}/pkg${bucket}"
  mkdir -p "${pkg_dir}"
  cat > "${pkg_dir}/file${i}.go" <<GO
// Code generated by scripts/generate-synthetic-corpus.sh; DO NOT EDIT.
package pkg${bucket}

import "fmt"

// Func${i} is a synthetic-corpus function for resource-pressure bench.
func Func${i}(x int) string {
	return fmt.Sprintf("synthetic-${i}-%d", x)
}

// Const${i} is a synthetic-corpus constant for extraction breadth.
var Const${i} = "synthetic-${i}"
GO
done

# go.mod at the corpus root so the indexer treats it as one project,
# not 100 sibling packages.
cat > "${OUT}/go.mod" <<GOMOD
module synthetic-corpus

go 1.21
GOMOD

# Init as a git repo so gocodewalker's .gitignore handling doesn't
# get confused. No actual gitignore — we WANT every file walked.
(cd "${OUT}" && git init --quiet && git -c user.email=bench@local -c user.name=bench add -A >/dev/null 2>&1 && git -c user.email=bench@local -c user.name=bench commit -m "synthetic-${COUNT}" --quiet)

echo "Generated ${COUNT} files under ${OUT}/ across 100 buckets."
